// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGdyRd8NIl8WmED9_gfgp05f_21RBuAIY',
    appId: '1:632076340870:web:7e9c9f8f68d659dbc8cb07',
    messagingSenderId: '632076340870',
    projectId: 'cash-driving',
    authDomain: 'cash-driving.firebaseapp.com',
    storageBucket: 'cash-driving.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbH0554I-s-EIiREGiKFbCQfvAEFctmB0',
    appId: '1:632076340870:android:1b0488c373d2affbc8cb07',
    messagingSenderId: '632076340870',
    projectId: 'cash-driving',
    storageBucket: 'cash-driving.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBepvEQKVCDeZtZVUchERav6sbRIDNSdus',
    appId: '1:632076340870:ios:d531cee3b4a3d693c8cb07',
    messagingSenderId: '632076340870',
    projectId: 'cash-driving',
    storageBucket: 'cash-driving.firebasestorage.app',
    iosBundleId: 'com.example.cashdriving',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBepvEQKVCDeZtZVUchERav6sbRIDNSdus',
    appId: '1:632076340870:ios:d531cee3b4a3d693c8cb07',
    messagingSenderId: '632076340870',
    projectId: 'cash-driving',
    storageBucket: 'cash-driving.firebasestorage.app',
    iosBundleId: 'com.example.cashdriving',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGdyRd8NIl8WmED9_gfgp05f_21RBuAIY',
    appId: '1:632076340870:web:72d5822fc102df2dc8cb07',
    messagingSenderId: '632076340870',
    projectId: 'cash-driving',
    authDomain: 'cash-driving.firebaseapp.com',
    storageBucket: 'cash-driving.firebasestorage.app',
  );
}
